version: '3.9'

services:
  postgres:
    image: 'postgres:16.2'
    container_name: 'planplus'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "ivanspasov"
      POSTGRES_PASSWORD: "psvmJkjk4922"
      POSTGRES_DB: "planplus"